theme="base16_transparent"
 
[editor]
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [120]
color-modes = true
cursorline = true
 
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":bn"
"S-tab" = ":bp"
X = "extend_line_above"
"C-j" = "copy_selection_on_next_line"
"C-k" = "copy_selection_on_prev_line"

# move current line up or down. Using A-C to escape conflicts
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

"A-x" = ["extend_to_line_bounds", "trim_selections", "change_selection"]
 
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
 
[editor.indent-guides]
render = true
 
[editor.file-picker]
hidden = true
git-ignore = true
 
[editor.lsp]
display-messages = false
 
[editor.statusline]
center = ["file-type"]

